//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace LegacyInternational.CruiseServiceRef {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CruiseServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CruiseService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RoomTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateBookingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CruiseService() {
            this.Url = global::LegacyInternational.Properties.Settings.Default.LegacyInternational_CruiseServiceRef_CruiseService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RoomTypesCompletedEventHandler RoomTypesCompleted;
        
        /// <remarks/>
        public event CreateBookingCompletedEventHandler CreateBookingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RoomTypes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] RoomTypes(string CheckIn, string CheckOut) {
            object[] results = this.Invoke("RoomTypes", new object[] {
                        CheckIn,
                        CheckOut});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void RoomTypesAsync(string CheckIn, string CheckOut) {
            this.RoomTypesAsync(CheckIn, CheckOut, null);
        }
        
        /// <remarks/>
        public void RoomTypesAsync(string CheckIn, string CheckOut, object userState) {
            if ((this.RoomTypesOperationCompleted == null)) {
                this.RoomTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRoomTypesOperationCompleted);
            }
            this.InvokeAsync("RoomTypes", new object[] {
                        CheckIn,
                        CheckOut}, this.RoomTypesOperationCompleted, userState);
        }
        
        private void OnRoomTypesOperationCompleted(object arg) {
            if ((this.RoomTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RoomTypesCompleted(this, new RoomTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateBooking", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateBooking(string username, string check_in_date, string check_out_date, int cruise_id, int booking_id, int room_num) {
            this.Invoke("CreateBooking", new object[] {
                        username,
                        check_in_date,
                        check_out_date,
                        cruise_id,
                        booking_id,
                        room_num});
        }
        
        /// <remarks/>
        public void CreateBookingAsync(string username, string check_in_date, string check_out_date, int cruise_id, int booking_id, int room_num) {
            this.CreateBookingAsync(username, check_in_date, check_out_date, cruise_id, booking_id, room_num, null);
        }
        
        /// <remarks/>
        public void CreateBookingAsync(string username, string check_in_date, string check_out_date, int cruise_id, int booking_id, int room_num, object userState) {
            if ((this.CreateBookingOperationCompleted == null)) {
                this.CreateBookingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateBookingOperationCompleted);
            }
            this.InvokeAsync("CreateBooking", new object[] {
                        username,
                        check_in_date,
                        check_out_date,
                        cruise_id,
                        booking_id,
                        room_num}, this.CreateBookingOperationCompleted, userState);
        }
        
        private void OnCreateBookingOperationCompleted(object arg) {
            if ((this.CreateBookingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateBookingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RoomTypesCompletedEventHandler(object sender, RoomTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoomTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RoomTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CreateBookingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591